-- Sweet Daisy — full database setup (generated by `npm run db:setup`; do not edit by hand).
-- Paste into Supabase → SQL Editor → Run, on a NEW project.

-- ===== 20261005000000_init.sql =====

-- Sweet Daisy — Cakes and Treats
-- Initial schema: catalogue, availability, orders, custom cake requests, newsletter and contact.
--
-- Security model
--   * The catalogue and availability are publicly readable.
--   * Orders can only be created through the `place_order` function, which re-prices every
--     line from the products table, so a tampered cart cannot change what the customer pays.
--   * Signed-in customers can read their own orders. Everything else is write-only for the public
--     and is managed from the Supabase dashboard (service role).


-- ---------------------------------------------------------------------------
-- Catalogue
-- ---------------------------------------------------------------------------

create table public.categories (
  id          text primary key,
  name        text not null,
  blurb       text not null default '',
  sort        int  not null default 0
);

create table public.products (
  slug          text primary key,
  name          text not null,
  category      text not null references public.categories (id),
  short         text not null default '',
  description   text not null default '',
  images        jsonb not null default '[]'::jsonb,   -- ["photo-key" | "/images/x.jpg" | "https://..."]
  sizes         jsonb not null default '[]'::jsonb,   -- [{id,label,servings,price}]
  flavors       jsonb not null default '[]'::jsonb,   -- [{label,price}]
  decorations   jsonb not null default '[]'::jsonb,   -- [{id,label,price}]
  allow_message boolean not null default false,
  lead_days     int not null default 1 check (lead_days >= 0),
  badge         text,
  bestseller    boolean not null default false,
  details       jsonb not null default '[]'::jsonb,   -- [{label,value}]
  tint          text not null default '#F4EDE1',
  sort          int not null default 0,
  active        boolean not null default true,
  created_at    timestamptz not null default now(),
  updated_at    timestamptz not null default now()
);

create index products_category_idx on public.products (category) where active;

-- Dates the studio is fully booked, has limited capacity, or is closed.
create table public.availability_overrides (
  day     date primary key,
  status  text not null check (status in ('limited', 'booked', 'closed')),
  note    text
);

-- ---------------------------------------------------------------------------
-- Orders
-- ---------------------------------------------------------------------------

create sequence public.order_number_seq start 10001;

create table public.orders (
  id                uuid primary key default gen_random_uuid(),
  order_number      text not null unique default ('SD-' || nextval('public.order_number_seq')),
  user_id           uuid references auth.users (id) on delete set null,
  status            text not null default 'received'
                      check (status in ('received', 'confirmed', 'baking', 'ready', 'completed', 'cancelled')),
  customer_name     text not null,
  email             text not null,
  phone             text not null,
  fulfillment       text not null check (fulfillment in ('pickup', 'delivery')),
  address           jsonb,
  fulfillment_date  date not null,
  time_slot         text not null,
  instructions      text,
  payment_method    text not null check (payment_method in ('card', 'in_person')),
  payment_status    text not null default 'pending' check (payment_status in ('pending', 'paid', 'refunded')),
  subtotal          numeric(10, 2) not null,
  delivery_fee      numeric(10, 2) not null default 0,
  total             numeric(10, 2) not null,
  created_at        timestamptz not null default now()
);

create index orders_user_idx on public.orders (user_id);
create index orders_date_idx on public.orders (fulfillment_date);

create table public.order_items (
  id            uuid primary key default gen_random_uuid(),
  order_id      uuid not null references public.orders (id) on delete cascade,
  product_slug  text not null references public.products (slug),
  product_name  text not null,
  size_label    text not null,
  flavor        text,
  decoration    text,
  message       text,
  notes         text,
  quantity      int not null check (quantity between 1 and 50),
  unit_price    numeric(10, 2) not null,
  line_total    numeric(10, 2) not null
);

create index order_items_order_idx on public.order_items (order_id);

-- ---------------------------------------------------------------------------
-- Custom cakes, newsletter, contact
-- ---------------------------------------------------------------------------

create table public.custom_cake_requests (
  id                uuid primary key default gen_random_uuid(),
  size              text not null,
  flavor            text not null,
  filling           text not null,
  frosting          text not null,
  decoration_style  text not null,
  inspiration_paths text[] not null default '{}',   -- objects in the `cake-inspiration` bucket
  event_date        date not null,
  occasion          text,
  instructions      text,
  name              text not null,
  email             text not null,
  phone             text,
  status            text not null default 'new' check (status in ('new', 'quoted', 'confirmed', 'declined')),
  created_at        timestamptz not null default now()
);

create table public.newsletter_subscribers (
  email       text primary key check (position('@' in email) > 1),
  created_at  timestamptz not null default now()
);

create table public.contact_messages (
  id          uuid primary key default gen_random_uuid(),
  name        text not null,
  email       text not null,
  topic       text,
  message     text not null,
  created_at  timestamptz not null default now()
);

-- ---------------------------------------------------------------------------
-- Row level security
-- ---------------------------------------------------------------------------

alter table public.categories             enable row level security;
alter table public.products               enable row level security;
alter table public.availability_overrides enable row level security;
alter table public.orders                 enable row level security;
alter table public.order_items            enable row level security;
alter table public.custom_cake_requests   enable row level security;
alter table public.newsletter_subscribers enable row level security;
alter table public.contact_messages       enable row level security;

create policy "Categories are public" on public.categories
  for select to anon, authenticated using (true);

create policy "Active products are public" on public.products
  for select to anon, authenticated using (active);

create policy "Availability is public" on public.availability_overrides
  for select to anon, authenticated using (true);

create policy "Customers read their own orders" on public.orders
  for select to authenticated using (user_id = (select auth.uid()));

create policy "Customers read their own order items" on public.order_items
  for select to authenticated
  using (exists (select 1 from public.orders o where o.id = order_id and o.user_id = (select auth.uid())));

create policy "Anyone can request a custom cake" on public.custom_cake_requests
  for insert to anon, authenticated with check (status = 'new');

create policy "Anyone can join the newsletter" on public.newsletter_subscribers
  for insert to anon, authenticated with check (true);

create policy "Anyone can send a message" on public.contact_messages
  for insert to anon, authenticated with check (true);

-- ---------------------------------------------------------------------------
-- place_order: validates the cart and the date, prices it server-side and stores it.
-- ---------------------------------------------------------------------------

create or replace function public.place_order(payload jsonb)
returns table (order_number text, total numeric)
language plpgsql
security definer
set search_path = ''
as $$
#variable_conflict use_column
declare
  v_order_id     uuid;
  v_number       text;
  v_item         jsonb;
  v_product      public.products%rowtype;
  v_size         jsonb;
  v_flavor_price numeric;
  v_deco_price   numeric;
  v_unit         numeric;
  v_qty          int;
  v_subtotal     numeric := 0;
  v_fee          numeric := 0;
  v_max_lead     int := 0;
  v_date         date := (payload ->> 'fulfillment_date')::date;
  v_fulfillment  text := payload ->> 'fulfillment';
begin
  if jsonb_typeof(payload -> 'items') <> 'array' or jsonb_array_length(payload -> 'items') = 0 then
    raise exception 'Your bag is empty.';
  end if;

  if extract(isodow from v_date) = 1 then
    raise exception 'We are closed on Mondays. Please choose another date.';
  end if;

  if exists (select 1 from public.availability_overrides a where a.day = v_date and a.status in ('booked', 'closed')) then
    raise exception 'That date is fully booked. Please choose another date.';
  end if;

  insert into public.orders (
    user_id, customer_name, email, phone, fulfillment, address, fulfillment_date, time_slot,
    instructions, payment_method, subtotal, delivery_fee, total
  ) values (
    auth.uid(),
    payload ->> 'customer_name',
    lower(payload ->> 'email'),
    payload ->> 'phone',
    v_fulfillment,
    case when v_fulfillment = 'delivery' then payload -> 'address' else null end,
    v_date,
    payload ->> 'time_slot',
    nullif(payload ->> 'instructions', ''),
    payload ->> 'payment_method',
    0, 0, 0
  )
  returning id, orders.order_number into v_order_id, v_number;

  for v_item in select * from jsonb_array_elements(payload -> 'items') loop
    select * into v_product from public.products p where p.slug = v_item ->> 'slug' and p.active;
    if not found then
      raise exception 'A product in your bag is no longer available.';
    end if;

    select s into v_size from jsonb_array_elements(v_product.sizes) s where s ->> 'id' = v_item ->> 'size_id';
    if v_size is null then
      raise exception 'Please choose a valid size for %.', v_product.name;
    end if;

    select coalesce((f ->> 'price')::numeric, 0) into v_flavor_price
      from jsonb_array_elements(v_product.flavors) f where f ->> 'label' = v_item ->> 'flavor';
    select coalesce((d ->> 'price')::numeric, 0) into v_deco_price
      from jsonb_array_elements(v_product.decorations) d where d ->> 'id' = v_item ->> 'decoration_id';

    v_qty  := greatest(1, least(50, coalesce((v_item ->> 'quantity')::int, 1)));
    v_unit := (v_size ->> 'price')::numeric + coalesce(v_flavor_price, 0) + coalesce(v_deco_price, 0);
    v_subtotal := v_subtotal + v_unit * v_qty;
    v_max_lead := greatest(v_max_lead, v_product.lead_days);

    insert into public.order_items (
      order_id, product_slug, product_name, size_label, flavor, decoration, message, notes,
      quantity, unit_price, line_total
    ) values (
      v_order_id, v_product.slug, v_product.name, v_size ->> 'label',
      nullif(v_item ->> 'flavor', ''),
      (select d ->> 'label' from jsonb_array_elements(v_product.decorations) d where d ->> 'id' = v_item ->> 'decoration_id'),
      left(nullif(v_item ->> 'message', ''), 60),
      left(nullif(v_item ->> 'notes', ''), 500),
      v_qty, v_unit, v_unit * v_qty
    );
  end loop;

  if v_date < current_date + v_max_lead then
    raise exception 'Some items need % days notice. Please choose a later date.', v_max_lead;
  end if;

  if v_fulfillment = 'delivery' and v_subtotal < 120 then
    v_fee := 12;
  end if;

  update public.orders o
     set subtotal = v_subtotal, delivery_fee = v_fee, total = v_subtotal + v_fee
   where o.id = v_order_id;

  return query select v_number, v_subtotal + v_fee;
end;
$$;

revoke all on function public.place_order(jsonb) from public;
grant execute on function public.place_order(jsonb) to anon, authenticated;

-- ---------------------------------------------------------------------------
-- Storage: inspiration images uploaded from the custom cake builder (private bucket).
-- ---------------------------------------------------------------------------

insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values ('cake-inspiration', 'cake-inspiration', false, 10485760, array['image/jpeg', 'image/png', 'image/webp', 'image/heic'])
on conflict (id) do nothing;

create policy "Anyone can upload cake inspiration" on storage.objects
  for insert to anon, authenticated
  with check (bucket_id = 'cake-inspiration');


-- ===== 20261005020000_admin.sql =====

-- Sweet Daisy — admin panel
-- Admin users, editable settings, admin RLS policies, product image storage, and a
-- settings-aware place_order.
--
-- To make someone an admin (after they have signed up once):
--   insert into public.admins (user_id, email)
--   select id, email from auth.users where email = 'owner@example.com';

-- ---------------------------------------------------------------------------
-- Admins
-- ---------------------------------------------------------------------------

create table public.admins (
  user_id    uuid primary key references auth.users (id) on delete cascade,
  email      text,
  created_at timestamptz not null default now()
);

alter table public.admins enable row level security;

create policy "Admins can see their own row" on public.admins
  for select to authenticated using (user_id = (select auth.uid()));

create or replace function public.is_admin()
returns boolean
language sql
stable
security definer
set search_path = ''
as $$
  select exists (select 1 from public.admins a where a.user_id = auth.uid());
$$;

grant execute on function public.is_admin() to anon, authenticated;

-- ---------------------------------------------------------------------------
-- Settings (business info, store rules, custom cake builder options)
-- ---------------------------------------------------------------------------

create table public.settings (
  key        text primary key check (key in ('business', 'store', 'custom')),
  value      jsonb not null,
  updated_at timestamptz not null default now()
);

alter table public.settings enable row level security;

create policy "Settings are public" on public.settings
  for select to anon, authenticated using (true);

-- ---------------------------------------------------------------------------
-- Admin-only columns
-- ---------------------------------------------------------------------------

-- 'open' re-opens a day that is normally closed (e.g. a Monday for a wedding).
alter table public.availability_overrides drop constraint availability_overrides_status_check;
alter table public.availability_overrides add constraint availability_overrides_status_check
  check (status in ('limited', 'booked', 'closed', 'open'));

alter table public.orders add column admin_notes text;
alter table public.custom_cake_requests add column quote_amount numeric(10, 2);
alter table public.custom_cake_requests add column admin_notes text;

-- The public may only create brand-new requests, never set admin fields.
drop policy "Anyone can request a custom cake" on public.custom_cake_requests;
create policy "Anyone can request a custom cake" on public.custom_cake_requests
  for insert to anon, authenticated
  with check (status = 'new' and quote_amount is null and admin_notes is null);

-- ---------------------------------------------------------------------------
-- Admin policies
-- ---------------------------------------------------------------------------

create policy "Admins manage categories" on public.categories
  for all to authenticated using (public.is_admin()) with check (public.is_admin());

create policy "Admins manage products" on public.products
  for all to authenticated using (public.is_admin()) with check (public.is_admin());

create policy "Admins manage availability" on public.availability_overrides
  for all to authenticated using (public.is_admin()) with check (public.is_admin());

create policy "Admins manage settings" on public.settings
  for all to authenticated using (public.is_admin()) with check (public.is_admin());

create policy "Admins read orders" on public.orders
  for select to authenticated using (public.is_admin());
create policy "Admins update orders" on public.orders
  for update to authenticated using (public.is_admin()) with check (public.is_admin());

create policy "Admins read order items" on public.order_items
  for select to authenticated using (public.is_admin());

create policy "Admins read custom requests" on public.custom_cake_requests
  for select to authenticated using (public.is_admin());
create policy "Admins update custom requests" on public.custom_cake_requests
  for update to authenticated using (public.is_admin()) with check (public.is_admin());
create policy "Admins delete custom requests" on public.custom_cake_requests
  for delete to authenticated using (public.is_admin());

create policy "Admins read messages" on public.contact_messages
  for select to authenticated using (public.is_admin());
create policy "Admins delete messages" on public.contact_messages
  for delete to authenticated using (public.is_admin());

create policy "Admins read subscribers" on public.newsletter_subscribers
  for select to authenticated using (public.is_admin());
create policy "Admins delete subscribers" on public.newsletter_subscribers
  for delete to authenticated using (public.is_admin());

-- ---------------------------------------------------------------------------
-- Storage: public product photos (admin-managed); admins can view inspiration uploads.
-- ---------------------------------------------------------------------------

insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values ('product-images', 'product-images', true, 8388608, array['image/jpeg', 'image/png', 'image/webp'])
on conflict (id) do nothing;

create policy "Admins upload product images" on storage.objects
  for insert to authenticated with check (bucket_id = 'product-images' and public.is_admin());
create policy "Admins update product images" on storage.objects
  for update to authenticated using (bucket_id = 'product-images' and public.is_admin());
create policy "Admins delete product images" on storage.objects
  for delete to authenticated using (bucket_id = 'product-images' and public.is_admin());

create policy "Admins view cake inspiration" on storage.objects
  for select to authenticated using (bucket_id = 'cake-inspiration' and public.is_admin());

-- ---------------------------------------------------------------------------
-- place_order now reads closed days, time slots and delivery pricing from settings.
-- ---------------------------------------------------------------------------

create or replace function public.place_order(payload jsonb)
returns table (order_number text, total numeric)
language plpgsql
security definer
set search_path = ''
as $$
#variable_conflict use_column
declare
  v_store        jsonb := coalesce((select s.value from public.settings s where s.key = 'store'), '{}'::jsonb);
  -- Missing setting => closed on Mondays; an explicitly empty list => open every day.
  v_closed       int[] := case when v_store ? 'closedWeekdays'
                            then array(select jsonb_array_elements_text(v_store -> 'closedWeekdays')::int)
                            else array[1] end;
  v_fee_amount   numeric := coalesce((v_store ->> 'deliveryFee')::numeric, 12);
  v_free_over    numeric := coalesce((v_store ->> 'freeDeliveryOver')::numeric, 120);
  v_slots        jsonb;
  v_order_id     uuid;
  v_number       text;
  v_item         jsonb;
  v_product      public.products%rowtype;
  v_size         jsonb;
  v_flavor_price numeric;
  v_deco_price   numeric;
  v_unit         numeric;
  v_qty          int;
  v_subtotal     numeric := 0;
  v_fee          numeric := 0;
  v_max_lead     int := 0;
  v_date         date := (payload ->> 'fulfillment_date')::date;
  v_fulfillment  text := payload ->> 'fulfillment';
begin
  if jsonb_typeof(payload -> 'items') <> 'array' or jsonb_array_length(payload -> 'items') = 0 then
    raise exception 'Your bag is empty.';
  end if;

  if extract(dow from v_date)::int = any (v_closed)
     and not exists (select 1 from public.availability_overrides a where a.day = v_date and a.status = 'open') then
    raise exception 'The studio is closed on that day. Please choose another date.';
  end if;

  if exists (select 1 from public.availability_overrides a where a.day = v_date and a.status in ('booked', 'closed')) then
    raise exception 'That date is fully booked. Please choose another date.';
  end if;

  v_slots := v_store -> (case when v_fulfillment = 'delivery' then 'deliverySlots' else 'pickupSlots' end);
  if jsonb_typeof(v_slots) = 'array' and not (v_slots ? (payload ->> 'time_slot')) then
    raise exception 'Please choose one of the available times.';
  end if;

  insert into public.orders (
    user_id, customer_name, email, phone, fulfillment, address, fulfillment_date, time_slot,
    instructions, payment_method, subtotal, delivery_fee, total
  ) values (
    auth.uid(),
    payload ->> 'customer_name',
    lower(payload ->> 'email'),
    payload ->> 'phone',
    v_fulfillment,
    case when v_fulfillment = 'delivery' then payload -> 'address' else null end,
    v_date,
    payload ->> 'time_slot',
    nullif(payload ->> 'instructions', ''),
    payload ->> 'payment_method',
    0, 0, 0
  )
  returning id, orders.order_number into v_order_id, v_number;

  for v_item in select * from jsonb_array_elements(payload -> 'items') loop
    select * into v_product from public.products p where p.slug = v_item ->> 'slug' and p.active;
    if not found then
      raise exception 'A product in your bag is no longer available.';
    end if;

    select s into v_size from jsonb_array_elements(v_product.sizes) s where s ->> 'id' = v_item ->> 'size_id';
    if v_size is null then
      raise exception 'Please choose a valid size for %.', v_product.name;
    end if;

    select coalesce((f ->> 'price')::numeric, 0) into v_flavor_price
      from jsonb_array_elements(v_product.flavors) f where f ->> 'label' = v_item ->> 'flavor';
    select coalesce((d ->> 'price')::numeric, 0) into v_deco_price
      from jsonb_array_elements(v_product.decorations) d where d ->> 'id' = v_item ->> 'decoration_id';

    v_qty  := greatest(1, least(50, coalesce((v_item ->> 'quantity')::int, 1)));
    v_unit := (v_size ->> 'price')::numeric + coalesce(v_flavor_price, 0) + coalesce(v_deco_price, 0);
    v_subtotal := v_subtotal + v_unit * v_qty;
    v_max_lead := greatest(v_max_lead, v_product.lead_days);

    insert into public.order_items (
      order_id, product_slug, product_name, size_label, flavor, decoration, message, notes,
      quantity, unit_price, line_total
    ) values (
      v_order_id, v_product.slug, v_product.name, v_size ->> 'label',
      nullif(v_item ->> 'flavor', ''),
      (select d ->> 'label' from jsonb_array_elements(v_product.decorations) d where d ->> 'id' = v_item ->> 'decoration_id'),
      left(nullif(v_item ->> 'message', ''), 60),
      left(nullif(v_item ->> 'notes', ''), 500),
      v_qty, v_unit, v_unit * v_qty
    );
  end loop;

  if v_date < current_date + v_max_lead then
    raise exception 'Some items need % days notice. Please choose a later date.', v_max_lead;
  end if;

  if v_fulfillment = 'delivery' and v_subtotal < v_free_over then
    v_fee := v_fee_amount;
  end if;

  update public.orders o
     set subtotal = v_subtotal, delivery_fee = v_fee, total = v_subtotal + v_fee
   where o.id = v_order_id;

  return query select v_number, v_subtotal + v_fee;
end;
$$;

revoke all on function public.place_order(jsonb) from public;
grant execute on function public.place_order(jsonb) to anon, authenticated;


-- ===== 20261006000000_prep_time.sql =====

-- Average preparation time per product (hours), set from /admin and shown to customers.
alter table public.products
  add column if not exists prep_hours numeric(6, 1) check (prep_hours is null or prep_hours >= 0);


-- ===== seed.sql =====

-- Generated by scripts/generate-seed.ts — do not edit by hand.

insert into public.categories (id, name, blurb, sort) values
  ('cakes', 'Cakes', 'Layered celebration cakes, finished by hand.', 0),
  ('mini-cakes', 'Mini Cakes', 'Small cakes for intimate celebrations.', 1),
  ('cupcakes', 'Cupcakes', 'Signature cupcakes, boxed to gift.', 2),
  ('treats', 'Treats', 'Macarons, cookies and dessert boxes.', 3),
  ('seasonal', 'Seasonal', 'Limited bakes inspired by the season.', 4)
on conflict (id) do update set name = excluded.name, blurb = excluded.blurb, sort = excluded.sort;

insert into public.products (slug, name, category, short, description, images, sizes, flavors, decorations, allow_message, lead_days, prep_hours, badge, bestseller, details, tint, sort) values
  ('strawberry-dream-cake', 'Strawberry Dream Cake', 'cakes', 'Vanilla sponge, fresh strawberries and whipped mascarpone cream.', 'Our most-requested cake. Three layers of light vanilla bean sponge, filled with macerated summer strawberries and a cloud of whipped mascarpone cream, finished with a soft-textured buttercream and a crown of fresh berries.', '["strawberry","sliced","celebration"]'::jsonb, '[{"id":"6in","label":"6\" round","servings":"8–10 servings","price":68},{"id":"8in","label":"8\" round","servings":"14–18 servings","price":94},{"id":"10in","label":"10\" round","servings":"24–30 servings","price":126}]'::jsonb, '[{"label":"Vanilla bean sponge","price":0},{"label":"Lemon sponge","price":0},{"label":"Gluten-free vanilla","price":8}]'::jsonb, '[{"id":"classic","label":"Classic Sweet Daisy finish","price":0},{"id":"fresh-flowers","label":"Fresh seasonal flowers","price":18},{"id":"gold-leaf","label":"Edible gold leaf accents","price":14},{"id":"berries","label":"Fresh berry crown","price":12}]'::jsonb, true, 2, 24, 'Bestseller', true, '[{"label":"Allergens","value":"Contains wheat, eggs, dairy. Made in a kitchen that handles nuts."},{"label":"Storage","value":"Keep refrigerated. Serve at room temperature — remove 1 hour before slicing."},{"label":"Best enjoyed","value":"Within 3 days of collection."}]'::jsonb, '#F2E3DC', 0),
  ('vanilla-daisy-cake', 'Vanilla Daisy Cake', 'cakes', 'Madagascar vanilla, silky Swiss meringue buttercream, piped daisies.', 'The cake our studio is named after. A buttery Madagascar vanilla sponge layered with silky Swiss meringue buttercream and a whisper of white chocolate ganache, hand-piped with delicate daisies.', '["vanilla","floral","hero"]'::jsonb, '[{"id":"6in","label":"6\" round","servings":"8–10 servings","price":64},{"id":"8in","label":"8\" round","servings":"14–18 servings","price":90},{"id":"10in","label":"10\" round","servings":"24–30 servings","price":122}]'::jsonb, '[{"label":"Vanilla bean sponge","price":0},{"label":"Almond sponge","price":0},{"label":"Gluten-free vanilla","price":8}]'::jsonb, '[{"id":"classic","label":"Classic Sweet Daisy finish","price":0},{"id":"fresh-flowers","label":"Fresh seasonal flowers","price":18},{"id":"gold-leaf","label":"Edible gold leaf accents","price":14},{"id":"berries","label":"Fresh berry crown","price":12}]'::jsonb, true, 2, 24, 'Signature', true, '[{"label":"Allergens","value":"Contains wheat, eggs, dairy. Made in a kitchen that handles nuts."},{"label":"Storage","value":"Keep refrigerated. Serve at room temperature — remove 1 hour before slicing."},{"label":"Best enjoyed","value":"Within 3 days of collection."}]'::jsonb, '#F4EDE1', 1),
  ('chocolate-velvet-cake', 'Chocolate Velvet Cake', 'cakes', 'Dark cocoa sponge, salted caramel and a glossy ganache drip.', 'For the chocolate devoted. Moist dark cocoa layers with a ribbon of house-made salted caramel, whipped milk chocolate ganache and a glossy 64% dark chocolate drip.', '["chocolate","chocolateAlt","sliced"]'::jsonb, '[{"id":"6in","label":"6\" round","servings":"8–10 servings","price":72},{"id":"8in","label":"8\" round","servings":"14–18 servings","price":98},{"id":"10in","label":"10\" round","servings":"24–30 servings","price":130}]'::jsonb, '[{"label":"Dark chocolate sponge","price":0},{"label":"Chocolate & hazelnut","price":0},{"label":"Gluten-free chocolate","price":8}]'::jsonb, '[{"id":"classic","label":"Classic Sweet Daisy finish","price":0},{"id":"fresh-flowers","label":"Fresh seasonal flowers","price":18},{"id":"gold-leaf","label":"Edible gold leaf accents","price":14},{"id":"berries","label":"Fresh berry crown","price":12}]'::jsonb, true, 2, 24, null, true, '[{"label":"Allergens","value":"Contains wheat, eggs, dairy. Made in a kitchen that handles nuts."},{"label":"Storage","value":"Keep refrigerated. Serve at room temperature — remove 1 hour before slicing."},{"label":"Best enjoyed","value":"Within 3 days of collection."}]'::jsonb, '#E6D8CA', 2),
  ('lemon-cream-cake', 'Lemon Cream Cake', 'cakes', 'Lemon chiffon, tangy curd and soft vanilla cream.', 'Bright and elegant. Feather-light lemon chiffon layered with tangy house-made lemon curd and vanilla chantilly, finished with candied lemon and tiny edible flowers.', '["lemon","floral","vanilla"]'::jsonb, '[{"id":"6in","label":"6\" round","servings":"8–10 servings","price":66},{"id":"8in","label":"8\" round","servings":"14–18 servings","price":92},{"id":"10in","label":"10\" round","servings":"24–30 servings","price":124}]'::jsonb, '[{"label":"Lemon chiffon","price":0},{"label":"Lemon & elderflower","price":0},{"label":"Gluten-free lemon","price":8}]'::jsonb, '[{"id":"classic","label":"Classic Sweet Daisy finish","price":0},{"id":"fresh-flowers","label":"Fresh seasonal flowers","price":18},{"id":"gold-leaf","label":"Edible gold leaf accents","price":14},{"id":"berries","label":"Fresh berry crown","price":12}]'::jsonb, true, 2, 24, null, true, '[{"label":"Allergens","value":"Contains wheat, eggs, dairy. Made in a kitchen that handles nuts."},{"label":"Storage","value":"Keep refrigerated. Serve at room temperature — remove 1 hour before slicing."},{"label":"Best enjoyed","value":"Within 3 days of collection."}]'::jsonb, '#F3EBCF', 3),
  ('pistachio-rose-cake', 'Pistachio Rose Cake', 'cakes', 'Pistachio sponge, raspberry and a delicate rose buttercream.', 'Our most romantic cake. Toasted pistachio sponge layered with raspberry compote and a softly perfumed rose buttercream, scattered with crushed pistachio and dried petals.', '["pistachio","floral","wedding"]'::jsonb, '[{"id":"6in","label":"6\" round","servings":"8–10 servings","price":74},{"id":"8in","label":"8\" round","servings":"14–18 servings","price":100},{"id":"10in","label":"10\" round","servings":"24–30 servings","price":132}]'::jsonb, '[{"label":"Pistachio sponge","price":0},{"label":"Vanilla sponge","price":0}]'::jsonb, '[{"id":"classic","label":"Classic Sweet Daisy finish","price":0},{"id":"fresh-flowers","label":"Fresh seasonal flowers","price":18},{"id":"gold-leaf","label":"Edible gold leaf accents","price":14},{"id":"berries","label":"Fresh berry crown","price":12}]'::jsonb, true, 3, 30, 'New', false, '[{"label":"Allergens","value":"Contains pistachio, wheat, eggs, dairy."},{"label":"Storage","value":"Keep refrigerated. Serve at room temperature — remove 1 hour before slicing."},{"label":"Best enjoyed","value":"Within 3 days of collection."}]'::jsonb, '#E3E5D3', 4),
  ('carrot-walnut-cake', 'Carrot & Walnut Cake', 'cakes', 'Spiced carrot sponge, toasted walnuts, cream cheese frosting.', 'A classic made beautifully. Warmly spiced carrot sponge with toasted walnuts and golden raisins, layered with a tangy cream cheese frosting and finished with a semi-naked texture.', '["carrot","sliced","studio"]'::jsonb, '[{"id":"6in","label":"6\" round","servings":"8–10 servings","price":62},{"id":"8in","label":"8\" round","servings":"14–18 servings","price":88},{"id":"10in","label":"10\" round","servings":"24–30 servings","price":120}]'::jsonb, '[{"label":"Classic with walnuts","price":0},{"label":"Nut-free","price":0}]'::jsonb, '[{"id":"classic","label":"Classic Sweet Daisy finish","price":0},{"id":"fresh-flowers","label":"Fresh seasonal flowers","price":18},{"id":"gold-leaf","label":"Edible gold leaf accents","price":14},{"id":"berries","label":"Fresh berry crown","price":12}]'::jsonb, true, 2, 24, null, false, '[{"label":"Allergens","value":"Contains walnuts, wheat, eggs, dairy."},{"label":"Storage","value":"Keep refrigerated. Serve at room temperature — remove 1 hour before slicing."},{"label":"Best enjoyed","value":"Within 3 days of collection."}]'::jsonb, '#EBDCC6', 5),
  ('mini-celebration-cake', 'Mini Celebration Cake', 'mini-cakes', 'A 4" cake for two to four — every bit as special.', 'All the ceremony of a full cake, sized for small moments. Choose your flavour and we will finish it with our signature textured buttercream and a hand-lettered message.', '["mini","birthday","floral"]'::jsonb, '[{"id":"4in","label":"4\" mini","servings":"2–4 servings","price":38},{"id":"5in","label":"5\" petite","servings":"4–6 servings","price":46}]'::jsonb, '[{"label":"Vanilla & strawberry","price":0},{"label":"Chocolate velvet","price":0},{"label":"Lemon cream","price":0},{"label":"Pistachio rose","price":0}]'::jsonb, '[{"id":"classic","label":"Classic Sweet Daisy finish","price":0},{"id":"fresh-flowers","label":"Fresh seasonal flowers","price":18},{"id":"gold-leaf","label":"Edible gold leaf accents","price":14}]'::jsonb, true, 1, 6, 'Bestseller', true, '[{"label":"Allergens","value":"Contains wheat, eggs, dairy. Made in a kitchen that handles nuts."},{"label":"Storage","value":"Keep refrigerated. Serve at room temperature — remove 1 hour before slicing."},{"label":"Best enjoyed","value":"Within 3 days of collection."}]'::jsonb, '#F2E6DA', 6),
  ('bento-heart-cake', 'Bento Heart Cake', 'mini-cakes', 'A heart-shaped mini cake in a keepsake gift box.', 'A sweet little love letter. A heart-shaped vanilla or chocolate mini cake, piped in vintage style and presented in our keepsake box — perfect for anniversaries and just-because moments.', '["birthday","mini"]'::jsonb, '[{"id":"one","label":"Heart mini","servings":"1–2 servings","price":32}]'::jsonb, '[{"label":"Vanilla & raspberry","price":0},{"label":"Chocolate velvet","price":0}]'::jsonb, '[]'::jsonb, true, 1, 4, null, false, '[{"label":"Allergens","value":"Contains wheat, eggs, dairy. Made in a kitchen that handles nuts."},{"label":"Storage","value":"Keep refrigerated. Serve at room temperature — remove 1 hour before slicing."},{"label":"Best enjoyed","value":"Within 3 days of collection."}]'::jsonb, '#F3E4DE', 7),
  ('signature-cupcake-box', 'Signature Cupcake Box', 'cupcakes', 'An assortment of our signature cupcakes, beautifully boxed.', 'Our signature flavours in one elegant box: vanilla daisy, chocolate velvet, strawberry dream and lemon cream — each one piped by hand and topped with a little detail.', '["cupcakes","cupcakesAlt","packaging"]'::jsonb, '[{"id":"box6","label":"Box of 6","servings":"6 cupcakes","price":36},{"id":"box12","label":"Box of 12","servings":"12 cupcakes","price":68},{"id":"box24","label":"Box of 24","servings":"24 cupcakes","price":128}]'::jsonb, '[{"label":"Signature assortment","price":0},{"label":"All vanilla daisy","price":0},{"label":"All chocolate velvet","price":0}]'::jsonb, '[]'::jsonb, true, 1, 5, null, true, '[{"label":"Allergens","value":"Contains wheat, eggs, dairy. Made in a kitchen that handles nuts."},{"label":"Storage","value":"Keep refrigerated. Serve at room temperature — remove 1 hour before slicing."},{"label":"Best enjoyed","value":"Within 3 days of collection."}]'::jsonb, '#F1E7DA', 8),
  ('vanilla-bean-cupcakes', 'Vanilla Bean Cupcakes', 'cupcakes', 'Classic vanilla with a swirl of silky buttercream.', 'Simple, perfect and loved by everyone. Madagascar vanilla cupcakes with a generous swirl of vanilla Swiss meringue buttercream and a sugar daisy.', '["cupcakesAlt","cupcakes"]'::jsonb, '[{"id":"box6","label":"Box of 6","servings":"6 cupcakes","price":32},{"id":"box12","label":"Box of 12","servings":"12 cupcakes","price":60}]'::jsonb, '[]'::jsonb, '[]'::jsonb, false, 1, 4, null, false, '[{"label":"Allergens","value":"Contains wheat, eggs, dairy. Made in a kitchen that handles nuts."},{"label":"Storage","value":"Keep refrigerated. Serve at room temperature — remove 1 hour before slicing."},{"label":"Best enjoyed","value":"Within 3 days of collection."}]'::jsonb, '#F5EEE2', 9),
  ('macaron-gift-box', 'Macaron Gift Box', 'treats', 'Delicate French macarons in seasonal flavours.', 'Crisp shells, chewy centres and silky fillings. A curated box of French macarons in our current flavours — salted caramel, pistachio, raspberry, lemon, vanilla and chocolate.', '["macarons","dessertBox"]'::jsonb, '[{"id":"box12","label":"Box of 12","servings":"12 macarons","price":34},{"id":"box24","label":"Box of 24","servings":"24 macarons","price":64}]'::jsonb, '[]'::jsonb, '[]'::jsonb, true, 1, 24, null, false, '[{"label":"Allergens","value":"Contains almonds, eggs, dairy. Naturally gluten-free."},{"label":"Storage","value":"Keep refrigerated. Serve at room temperature — remove 1 hour before slicing."},{"label":"Best enjoyed","value":"Within 3 days of collection."}]'::jsonb, '#EEE6D6', 10),
  ('sweet-daisy-dessert-box', 'Sweet Daisy Dessert Box', 'treats', 'Mini tarts, macarons, cookies and cake bites to share.', 'A grazing box for gatherings: mini fruit tarts, macarons, brown butter cookies and bite-sized cake squares, arranged by hand and wrapped with ribbon.', '["dessertBox","tart","cookies"]'::jsonb, '[{"id":"small","label":"Petite box","servings":"Serves 4–6","price":48},{"id":"large","label":"Grand box","servings":"Serves 10–12","price":92}]'::jsonb, '[]'::jsonb, '[]'::jsonb, true, 2, 8, 'Gift favourite', false, '[{"label":"Allergens","value":"Contains wheat, eggs, dairy. Made in a kitchen that handles nuts."},{"label":"Storage","value":"Keep refrigerated. Serve at room temperature — remove 1 hour before slicing."},{"label":"Best enjoyed","value":"Within 3 days of collection."}]'::jsonb, '#EFE5D3', 11),
  ('brown-butter-cookies', 'Brown Butter Cookies', 'treats', 'Chewy brown butter cookies with dark chocolate and sea salt.', 'Thick, chewy cookies made with nutty brown butter, chunks of dark chocolate and a sprinkle of flaky sea salt. Baked fresh every morning.', '["cookies","packaging"]'::jsonb, '[{"id":"box6","label":"Box of 6","servings":"6 cookies","price":18},{"id":"box12","label":"Box of 12","servings":"12 cookies","price":34}]'::jsonb, '[]'::jsonb, '[]'::jsonb, false, 0, 2, null, false, '[{"label":"Allergens","value":"Contains wheat, eggs, dairy. Made in a kitchen that handles nuts."},{"label":"Storage","value":"Keep refrigerated. Serve at room temperature — remove 1 hour before slicing."},{"label":"Best enjoyed","value":"Within 3 days of collection."}]'::jsonb, '#E9DCC8', 12),
  ('berry-tartlets', 'Berry Tartlets', 'treats', 'Butter pastry, vanilla crème pâtissière and fresh berries.', 'Crisp, buttery pastry shells filled with vanilla crème pâtissière and topped with glazed fresh berries. A little bit of Paris in every bite.', '["tart","seasonal"]'::jsonb, '[{"id":"box4","label":"Box of 4","servings":"4 tartlets","price":26},{"id":"box8","label":"Box of 8","servings":"8 tartlets","price":48}]'::jsonb, '[]'::jsonb, '[]'::jsonb, false, 1, 5, null, false, '[{"label":"Allergens","value":"Contains wheat, eggs, dairy. Made in a kitchen that handles nuts."},{"label":"Storage","value":"Keep refrigerated. Serve at room temperature — remove 1 hour before slicing."},{"label":"Best enjoyed","value":"Within 3 days of collection."}]'::jsonb, '#F1E2DA', 13),
  ('autumn-spice-cake', 'Autumn Spice Cake', 'seasonal', 'Brown sugar spice, poached pear and maple cream.', 'Available for a limited time. Brown sugar and cinnamon sponge layered with vanilla-poached pears and a silky maple cream cheese frosting, finished with caramelised pecans.', '["seasonal","carrot","sliced"]'::jsonb, '[{"id":"6in","label":"6\" round","servings":"8–10 servings","price":70},{"id":"8in","label":"8\" round","servings":"14–18 servings","price":96},{"id":"10in","label":"10\" round","servings":"24–30 servings","price":128}]'::jsonb, '[{"label":"Spice & pear","price":0},{"label":"Spice & apple","price":0}]'::jsonb, '[{"id":"classic","label":"Classic Sweet Daisy finish","price":0},{"id":"fresh-flowers","label":"Fresh seasonal flowers","price":18},{"id":"gold-leaf","label":"Edible gold leaf accents","price":14},{"id":"berries","label":"Fresh berry crown","price":12}]'::jsonb, true, 2, 24, 'Limited', false, '[{"label":"Allergens","value":"Contains pecans, wheat, eggs, dairy."},{"label":"Storage","value":"Keep refrigerated. Serve at room temperature — remove 1 hour before slicing."},{"label":"Best enjoyed","value":"Within 3 days of collection."}]'::jsonb, '#EADBC2', 14),
  ('seasonal-treat-box', 'Seasonal Treat Box', 'seasonal', 'A rotating selection of our limited-edition bakes.', 'Our pastry team’s favourite seasonal creations in one box — expect spiced cookies, fruit tartlets, mini cakes and something new each month.', '["dessertBox","seasonal","macarons"]'::jsonb, '[{"id":"box","label":"Seasonal box","servings":"Serves 4–6","price":54}]'::jsonb, '[]'::jsonb, '[]'::jsonb, true, 2, 10, 'Limited', false, '[{"label":"Allergens","value":"Contains wheat, eggs, dairy. Made in a kitchen that handles nuts."},{"label":"Storage","value":"Keep refrigerated. Serve at room temperature — remove 1 hour before slicing."},{"label":"Best enjoyed","value":"Within 3 days of collection."}]'::jsonb, '#ECE1CB', 15)
on conflict (slug) do update set name = excluded.name, category = excluded.category, short = excluded.short,
  description = excluded.description, images = excluded.images, sizes = excluded.sizes, flavors = excluded.flavors,
  decorations = excluded.decorations, allow_message = excluded.allow_message, lead_days = excluded.lead_days, prep_hours = excluded.prep_hours,
  badge = excluded.badge, bestseller = excluded.bestseller, details = excluded.details, tint = excluded.tint,
  sort = excluded.sort, updated_at = now();

insert into public.settings (key, value) values
  ('business', '{"email":"hello@sweetdaisycakes.com","phone":"+1 (555) 014-2290","address":{"street":"214 Magnolia Street","city":"Austin","region":"TX","postal":"78704","country":"US"},"hours":[{"days":"Tuesday – Friday","time":"9:00 – 18:00"},{"days":"Saturday","time":"9:00 – 17:00"},{"days":"Sunday","time":"10:00 – 14:00"},{"days":"Monday","time":"Closed — baking day"}],"instagram":"https://instagram.com/sweetdaisy","facebook":"https://facebook.com/sweetdaisy","tiktok":"https://tiktok.com/@sweetdaisy","handle":"@sweetdaisy","announcement":"Order 48 hours ahead for celebration cakes"}'::jsonb),
  ('store', '{"closedWeekdays":[1],"deliveryFee":12,"freeDeliveryOver":120,"deliveryRadius":"within 15 miles of the studio","pickupSlots":["9:00 – 11:00","11:00 – 13:00","13:00 – 15:00","15:00 – 17:00"],"deliverySlots":["10:00 – 13:00","13:00 – 16:00","16:00 – 18:00"]}'::jsonb),
  ('custom', '{"leadDays":7,"depositPercent":30,"sizes":[{"label":"6\" round","servings":"8–10 servings","price":95},{"label":"8\" round","servings":"14–18 servings","price":135},{"label":"10\" round","servings":"24–30 servings","price":185},{"label":"Two tiers","servings":"30–45 servings","price":320},{"label":"Three tiers","servings":"60–90 servings","price":520}],"flavors":["Vanilla bean","Dark chocolate","Lemon chiffon","Red velvet","Pistachio","Spiced carrot","Almond & orange","Gluten-free vanilla"],"fillings":["Fresh strawberries & cream","Raspberry compote","Lemon curd","Salted caramel","Chocolate ganache","Passion fruit curd","Cream cheese","Buttercream only"],"frostings":[{"label":"Swiss meringue buttercream","note":"Silky, light, not too sweet"},{"label":"Cream cheese frosting","note":"Tangy and rich"},{"label":"Whipped mascarpone","note":"Soft and creamy"},{"label":"Chocolate ganache","note":"Glossy and decadent"},{"label":"Semi-naked","note":"Rustic, layers peek through"}],"styles":[{"label":"Minimal & textured","image":"vanilla","extra":0},{"label":"Fresh florals","image":"floral","extra":35},{"label":"Vintage piping","image":"birthday","extra":25},{"label":"Fruit crown","image":"strawberry","extra":20},{"label":"Gold & hand-painted","image":"wedding","extra":45},{"label":"Sculptural & modern","image":"pistachio","extra":40}],"occasions":["Birthday","Wedding","Anniversary","Baby shower","Engagement","Corporate event","Just because","Other"]}'::jsonb)
on conflict (key) do nothing;
