// Generates supabase/seed.sql from the local catalogue in src/data/products.ts.
// Usage: npm run db:seed
import { categories, products } from '../src/data/products.ts';

const q = (v: string | null | undefined) => (v == null ? 'null' : `'${v.replace(/'/g, "''")}'`);
const j = (v: unknown) => `${q(JSON.stringify(v ?? []))}::jsonb`;

const lines: string[] = ['-- Generated by scripts/generate-seed.ts — do not edit by hand.', ''];

lines.push('insert into public.categories (id, name, blurb, sort) values');
lines.push(
  categories.map((c, i) => `  (${q(c.id)}, ${q(c.name)}, ${q(c.blurb)}, ${i})`).join(',\n') +
    '\non conflict (id) do update set name = excluded.name, blurb = excluded.blurb, sort = excluded.sort;',
  '',
);

lines.push(
  'insert into public.products (slug, name, category, short, description, images, sizes, flavors, decorations, allow_message, lead_days, badge, bestseller, details, tint, sort) values',
);
lines.push(
  products
    .map(
      (p, i) =>
        `  (${q(p.slug)}, ${q(p.name)}, ${q(p.category)}, ${q(p.short)}, ${q(p.description)}, ${j(p.images)}, ${j(p.sizes)}, ${j(p.flavors)}, ${j(p.decorations)}, ${!!p.message}, ${p.leadDays}, ${q(p.badge)}, ${!!p.bestseller}, ${j(p.details)}, ${q(p.tint)}, ${i})`,
    )
    .join(',\n') +
    `\non conflict (slug) do update set name = excluded.name, category = excluded.category, short = excluded.short,
  description = excluded.description, images = excluded.images, sizes = excluded.sizes, flavors = excluded.flavors,
  decorations = excluded.decorations, allow_message = excluded.allow_message, lead_days = excluded.lead_days,
  badge = excluded.badge, bestseller = excluded.bestseller, details = excluded.details, tint = excluded.tint,
  sort = excluded.sort, updated_at = now();`,
);

console.log(lines.join('\n'));
