// Generates supabase/seed.sql from the local catalogue in src/data/products.ts.
// Usage: npm run db:seed  (or npm run db:setup to also rebuild supabase/setup.sql)
import { categories, products } from '../src/data/products.ts';
import { defaultSettings } from '../src/data/settings.ts';

const q = (v: string | null | undefined) => (v == null ? 'null' : `'${v.replace(/'/g, "''")}'`);
const j = (v: unknown) => `${q(JSON.stringify(v ?? []))}::jsonb`;
const jo = (v: unknown) => `${q(JSON.stringify(v ?? {}))}::jsonb`;

const lines: string[] = ['-- Generated by scripts/generate-seed.ts — do not edit by hand.', ''];

lines.push('insert into public.categories (id, name, blurb, sort, i18n) values');
lines.push(
  categories.map((c, i) => `  (${q(c.id)}, ${q(c.name)}, ${q(c.blurb)}, ${i}, ${jo(c.i18n)})`).join(',\n') +
    '\non conflict (id) do update set name = excluded.name, blurb = excluded.blurb, sort = excluded.sort, i18n = excluded.i18n;',
  '',
);

lines.push(
  'insert into public.products (slug, name, category, short, description, images, sizes, flavors, decorations, allow_message, lead_days, prep_hours, badge, bestseller, details, tint, sort, active, i18n) values',
);
lines.push(
  products
    .map(
      (p, i) =>
        `  (${q(p.slug)}, ${q(p.name)}, ${q(p.category)}, ${q(p.short)}, ${q(p.description)}, ${j(p.images)}, ${j(p.sizes)}, ${j(p.flavors)}, ${j(p.decorations)}, ${!!p.message}, ${p.leadDays}, ${p.prepHours ?? 'null'}, ${q(p.badge)}, ${!!p.bestseller}, ${j(p.details)}, ${q(p.tint)}, ${p.sort ?? i}, ${p.active !== false}, ${jo(p.i18n)})`,
    )
    .join(',\n') +
    `\non conflict (slug) do update set name = excluded.name, category = excluded.category, short = excluded.short,
  description = excluded.description, images = excluded.images, sizes = excluded.sizes, flavors = excluded.flavors,
  decorations = excluded.decorations, allow_message = excluded.allow_message, lead_days = excluded.lead_days, prep_hours = excluded.prep_hours,
  badge = excluded.badge, bestseller = excluded.bestseller, details = excluded.details, tint = excluded.tint,
  sort = excluded.sort, i18n = excluded.i18n, updated_at = now();
-- active is only set for new rows, so re-seeding never undoes products switched on or off in /admin.`,
);

lines.push(
  '',
  'insert into public.settings (key, value) values',
  Object.entries(defaultSettings)
    .map(([k, v]) => `  (${q(k)}, ${j(v)})`)
    .join(',\n') + '\non conflict (key) do nothing;',
);

console.log(lines.join('\n'));
