-- Cookies become the main line: add the NY cookie category and products, hide the earlier lines.
insert into public.categories (id, name, blurb, sort) values
  ('cookies', 'NY Cookies', 'Big, gooey New York–style cookies, boxed in 2s, 4s and 6s.', -1)
on conflict (id) do nothing;

insert into public.products (slug, name, category, short, description, images, sizes, flavors, decorations, allow_message, lead_days, prep_hours, badge, bestseller, details, tint, sort, active) values
  ('build-your-box', 'Build Your Own Box', 'cookies', 'Mix and match any flavours in a pack of 2, 4 or 6.', 'Can’t choose just one? Pick your pack size, then fill it with any mix of our cookie flavours. Boxed and ribboned, ready to gift.', '["packaging","cookies"]'::jsonb, '[{"id":"pack2","label":"Pack of 2","servings":"2 cookies","price":10},{"id":"pack4","label":"Pack of 4","servings":"4 cookies","price":19},{"id":"pack6","label":"Pack of 6","servings":"6 cookies","price":27}]'::jsonb, '[{"label":"Classic Chocolate Chip","price":0},{"label":"Double Chocolate Fudge","price":0},{"label":"Biscoff Crumble","price":0},{"label":"Red Velvet Cheesecake","price":0},{"label":"S’mores","price":0},{"label":"Birthday Funfetti","price":0}]'::jsonb, '[]'::jsonb, false, 1, 3, 'Mix & match', true, '[{"label":"Allergens","value":"Contains wheat, eggs, dairy. Made in a kitchen that handles nuts."},{"label":"Size","value":"Each cookie is about 5 oz — thick, crisp at the edges and soft in the middle."},{"label":"Storage","value":"Keep in the box at room temperature for up to 3 days. Warm for 5 minutes at 350°F for that just-baked feel."}]'::jsonb, '#EFEEE6', 0, true),
  ('classic-chocolate-chip', 'Classic Chocolate Chip', 'cookies', 'Brown butter dough, dark chocolate chunks and flaky sea salt.', 'The one that started it all. A thick New York–style cookie made with nutty brown butter and loaded with puddles of dark and milk chocolate, finished with flaky sea salt.', '["cookies","packaging"]'::jsonb, '[{"id":"pack2","label":"Pack of 2","servings":"2 cookies","price":10},{"id":"pack4","label":"Pack of 4","servings":"4 cookies","price":19},{"id":"pack6","label":"Pack of 6","servings":"6 cookies","price":27}]'::jsonb, '[]'::jsonb, '[]'::jsonb, false, 1, 3, 'Bestseller', true, '[{"label":"Allergens","value":"Contains wheat, eggs, dairy. Made in a kitchen that handles nuts."},{"label":"Size","value":"Each cookie is about 5 oz — thick, crisp at the edges and soft in the middle."},{"label":"Storage","value":"Keep in the box at room temperature for up to 3 days. Warm for 5 minutes at 350°F for that just-baked feel."}]'::jsonb, '#F6E7E3', 1, true),
  ('double-chocolate-fudge', 'Double Chocolate Fudge', 'cookies', 'Dark cocoa dough with a molten fudge centre.', 'For serious chocolate lovers: a deep cocoa cookie studded with white and dark chocolate, hiding a soft, molten fudge centre.', '["cookies","packaging"]'::jsonb, '[{"id":"pack2","label":"Pack of 2","servings":"2 cookies","price":10},{"id":"pack4","label":"Pack of 4","servings":"4 cookies","price":19},{"id":"pack6","label":"Pack of 6","servings":"6 cookies","price":27}]'::jsonb, '[]'::jsonb, '[]'::jsonb, false, 1, 3, null, true, '[{"label":"Allergens","value":"Contains wheat, eggs, dairy. Made in a kitchen that handles nuts."},{"label":"Size","value":"Each cookie is about 5 oz — thick, crisp at the edges and soft in the middle."},{"label":"Storage","value":"Keep in the box at room temperature for up to 3 days. Warm for 5 minutes at 350°F for that just-baked feel."}]'::jsonb, '#EFEEE6', 2, true),
  ('biscoff-crumble', 'Biscoff Crumble', 'cookies', 'Cookie-butter centre, white chocolate and Biscoff crumb.', 'A brown sugar cookie stuffed with a gooey Biscoff cookie-butter centre, topped with white chocolate and crushed Lotus biscuits.', '["cookies","packaging"]'::jsonb, '[{"id":"pack2","label":"Pack of 2","servings":"2 cookies","price":10},{"id":"pack4","label":"Pack of 4","servings":"4 cookies","price":19},{"id":"pack6","label":"Pack of 6","servings":"6 cookies","price":27}]'::jsonb, '[]'::jsonb, '[]'::jsonb, false, 1, 3, 'Fan favourite', true, '[{"label":"Allergens","value":"Contains wheat, eggs, dairy. Made in a kitchen that handles nuts."},{"label":"Size","value":"Each cookie is about 5 oz — thick, crisp at the edges and soft in the middle."},{"label":"Storage","value":"Keep in the box at room temperature for up to 3 days. Warm for 5 minutes at 350°F for that just-baked feel."}]'::jsonb, '#F6E7E3', 3, true),
  ('red-velvet-cheesecake', 'Red Velvet Cheesecake', 'cookies', 'Cocoa red velvet with a cream cheese heart.', 'Soft red velvet dough with white chocolate chips, wrapped around a tangy, creamy cheesecake centre.', '["cookies","packaging"]'::jsonb, '[{"id":"pack2","label":"Pack of 2","servings":"2 cookies","price":10},{"id":"pack4","label":"Pack of 4","servings":"4 cookies","price":19},{"id":"pack6","label":"Pack of 6","servings":"6 cookies","price":27}]'::jsonb, '[]'::jsonb, '[]'::jsonb, false, 1, 3, null, true, '[{"label":"Allergens","value":"Contains wheat, eggs, dairy. Made in a kitchen that handles nuts."},{"label":"Size","value":"Each cookie is about 5 oz — thick, crisp at the edges and soft in the middle."},{"label":"Storage","value":"Keep in the box at room temperature for up to 3 days. Warm for 5 minutes at 350°F for that just-baked feel."}]'::jsonb, '#EFEEE6', 4, true),
  ('smores', 'S’mores', 'cookies', 'Graham dough, milk chocolate and toasted marshmallow.', 'Campfire in a cookie: graham cracker dough, milk chocolate chunks and a gooey marshmallow centre, toasted on top.', '["cookies","packaging"]'::jsonb, '[{"id":"pack2","label":"Pack of 2","servings":"2 cookies","price":10},{"id":"pack4","label":"Pack of 4","servings":"4 cookies","price":19},{"id":"pack6","label":"Pack of 6","servings":"6 cookies","price":27}]'::jsonb, '[]'::jsonb, '[]'::jsonb, false, 1, 3, null, false, '[{"label":"Allergens","value":"Contains wheat, eggs, dairy. Made in a kitchen that handles nuts."},{"label":"Size","value":"Each cookie is about 5 oz — thick, crisp at the edges and soft in the middle."},{"label":"Storage","value":"Keep in the box at room temperature for up to 3 days. Warm for 5 minutes at 350°F for that just-baked feel."}]'::jsonb, '#F6E7E3', 5, true),
  ('birthday-funfetti', 'Birthday Funfetti', 'cookies', 'Vanilla dough, rainbow sprinkles and white chocolate.', 'Every day is a celebration: buttery vanilla dough packed with rainbow sprinkles and creamy white chocolate.', '["cookies","packaging"]'::jsonb, '[{"id":"pack2","label":"Pack of 2","servings":"2 cookies","price":10},{"id":"pack4","label":"Pack of 4","servings":"4 cookies","price":19},{"id":"pack6","label":"Pack of 6","servings":"6 cookies","price":27}]'::jsonb, '[]'::jsonb, '[]'::jsonb, false, 1, 3, null, false, '[{"label":"Allergens","value":"Contains wheat, eggs, dairy. Made in a kitchen that handles nuts."},{"label":"Size","value":"Each cookie is about 5 oz — thick, crisp at the edges and soft in the middle."},{"label":"Storage","value":"Keep in the box at room temperature for up to 3 days. Warm for 5 minutes at 350°F for that just-baked feel."}]'::jsonb, '#EFEEE6', 6, true)
on conflict (slug) do nothing;

update public.products set active = false, bestseller = false
 where category in ('cakes', 'mini-cakes', 'cupcakes', 'treats', 'seasonal');

update public.settings
   set value = jsonb_set(value, '{announcement}', to_jsonb('Order a day ahead for fresh-baked cookies'::text))
 where key = 'business' and value->>'announcement' = 'Order 48 hours ahead for celebration cakes';
