-- Spanish copy for the cookie line and the storefront settings (only where none is set yet).
update public.categories set i18n = '{"es":{"name":"Galletas NY","blurb":"Galletas grandes y suaves estilo New York, en cajas de 2, 4 y 6."}}'::jsonb where id = 'cookies' and i18n = '{}'::jsonb;
update public.products set i18n = '{"es":{"name":"Arma tu caja","short":"Combina los sabores que quieras en un paquete de 2, 4 o 6.","description":"¿No puedes elegir solo una? Elige el tamaño de tu paquete y llénalo con la combinación de sabores que quieras. Va en caja y con lazo, lista para regalar.","badge":"Combina sabores","sizes":{"pack2":{"label":"Paquete de 2","servings":"2 galletas"},"pack4":{"label":"Paquete de 4","servings":"4 galletas"},"pack6":{"label":"Paquete de 6","servings":"6 galletas"}},"details":[{"label":"Alérgenos","value":"Contiene trigo, huevo y lácteos. Hecho en una cocina que maneja frutos secos."},{"label":"Tamaño","value":"Cada galleta pesa unas 5 oz — gruesa, crujiente por fuera y suave por dentro."},{"label":"Conservación","value":"Guárdalas en la caja a temperatura ambiente hasta 3 días. Caliéntalas 5 minutos a 350 °F para que sepan recién horneadas."}]}}'::jsonb where slug = 'build-your-box' and i18n = '{}'::jsonb;
update public.products set i18n = '{"es":{"name":"Chispas de chocolate clásica","short":"Masa de mantequilla tostada, trozos de chocolate oscuro y sal en escamas.","description":"La que empezó todo. Una galleta gruesa estilo New York hecha con mantequilla tostada y llena de charcos de chocolate oscuro y con leche, terminada con sal en escamas.","badge":"La más vendida","sizes":{"pack2":{"label":"Paquete de 2","servings":"2 galletas"},"pack4":{"label":"Paquete de 4","servings":"4 galletas"},"pack6":{"label":"Paquete de 6","servings":"6 galletas"}},"details":[{"label":"Alérgenos","value":"Contiene trigo, huevo y lácteos. Hecho en una cocina que maneja frutos secos."},{"label":"Tamaño","value":"Cada galleta pesa unas 5 oz — gruesa, crujiente por fuera y suave por dentro."},{"label":"Conservación","value":"Guárdalas en la caja a temperatura ambiente hasta 3 días. Caliéntalas 5 minutos a 350 °F para que sepan recién horneadas."}]}}'::jsonb where slug = 'classic-chocolate-chip' and i18n = '{}'::jsonb;
update public.products set i18n = '{"es":{"name":"Doble chocolate fudge","short":"Masa de cacao oscuro con centro de fudge fundido.","description":"Para los amantes del chocolate: una galleta de cacao intenso con chocolate blanco y oscuro, que esconde un centro suave de fudge fundido.","sizes":{"pack2":{"label":"Paquete de 2","servings":"2 galletas"},"pack4":{"label":"Paquete de 4","servings":"4 galletas"},"pack6":{"label":"Paquete de 6","servings":"6 galletas"}},"details":[{"label":"Alérgenos","value":"Contiene trigo, huevo y lácteos. Hecho en una cocina que maneja frutos secos."},{"label":"Tamaño","value":"Cada galleta pesa unas 5 oz — gruesa, crujiente por fuera y suave por dentro."},{"label":"Conservación","value":"Guárdalas en la caja a temperatura ambiente hasta 3 días. Caliéntalas 5 minutos a 350 °F para que sepan recién horneadas."}]}}'::jsonb where slug = 'double-chocolate-fudge' and i18n = '{}'::jsonb;
update public.products set i18n = '{"es":{"name":"Biscoff crumble","short":"Centro de crema Biscoff, chocolate blanco y galleta Biscoff triturada.","description":"Una galleta de azúcar morena rellena de crema de galleta Biscoff, cubierta con chocolate blanco y galletas Lotus trituradas.","badge":"Favorita de los clientes","sizes":{"pack2":{"label":"Paquete de 2","servings":"2 galletas"},"pack4":{"label":"Paquete de 4","servings":"4 galletas"},"pack6":{"label":"Paquete de 6","servings":"6 galletas"}},"details":[{"label":"Alérgenos","value":"Contiene trigo, huevo y lácteos. Hecho en una cocina que maneja frutos secos."},{"label":"Tamaño","value":"Cada galleta pesa unas 5 oz — gruesa, crujiente por fuera y suave por dentro."},{"label":"Conservación","value":"Guárdalas en la caja a temperatura ambiente hasta 3 días. Caliéntalas 5 minutos a 350 °F para que sepan recién horneadas."}]}}'::jsonb where slug = 'biscoff-crumble' and i18n = '{}'::jsonb;
update public.products set i18n = '{"es":{"name":"Red velvet con cheesecake","short":"Red velvet de cacao con corazón de queso crema.","description":"Masa suave de red velvet con chispas de chocolate blanco, envolviendo un centro cremoso de cheesecake.","sizes":{"pack2":{"label":"Paquete de 2","servings":"2 galletas"},"pack4":{"label":"Paquete de 4","servings":"4 galletas"},"pack6":{"label":"Paquete de 6","servings":"6 galletas"}},"details":[{"label":"Alérgenos","value":"Contiene trigo, huevo y lácteos. Hecho en una cocina que maneja frutos secos."},{"label":"Tamaño","value":"Cada galleta pesa unas 5 oz — gruesa, crujiente por fuera y suave por dentro."},{"label":"Conservación","value":"Guárdalas en la caja a temperatura ambiente hasta 3 días. Caliéntalas 5 minutos a 350 °F para que sepan recién horneadas."}]}}'::jsonb where slug = 'red-velvet-cheesecake' and i18n = '{}'::jsonb;
update public.products set i18n = '{"es":{"name":"S’mores","short":"Masa de galleta graham, chocolate con leche y malvavisco tostado.","description":"Una fogata en una galleta: masa de galleta graham, trozos de chocolate con leche y un centro de malvavisco, tostado por encima.","sizes":{"pack2":{"label":"Paquete de 2","servings":"2 galletas"},"pack4":{"label":"Paquete de 4","servings":"4 galletas"},"pack6":{"label":"Paquete de 6","servings":"6 galletas"}},"details":[{"label":"Alérgenos","value":"Contiene trigo, huevo y lácteos. Hecho en una cocina que maneja frutos secos."},{"label":"Tamaño","value":"Cada galleta pesa unas 5 oz — gruesa, crujiente por fuera y suave por dentro."},{"label":"Conservación","value":"Guárdalas en la caja a temperatura ambiente hasta 3 días. Caliéntalas 5 minutos a 350 °F para que sepan recién horneadas."}]}}'::jsonb where slug = 'smores' and i18n = '{}'::jsonb;
update public.products set i18n = '{"es":{"name":"Funfetti de cumpleaños","short":"Masa de vainilla, chispas de colores y chocolate blanco.","description":"Cada día es una celebración: masa de vainilla con mantequilla, llena de chispas de colores y chocolate blanco cremoso.","sizes":{"pack2":{"label":"Paquete de 2","servings":"2 galletas"},"pack4":{"label":"Paquete de 4","servings":"4 galletas"},"pack6":{"label":"Paquete de 6","servings":"6 galletas"}},"details":[{"label":"Alérgenos","value":"Contiene trigo, huevo y lácteos. Hecho en una cocina que maneja frutos secos."},{"label":"Tamaño","value":"Cada galleta pesa unas 5 oz — gruesa, crujiente por fuera y suave por dentro."},{"label":"Conservación","value":"Guárdalas en la caja a temperatura ambiente hasta 3 días. Caliéntalas 5 minutos a 350 °F para que sepan recién horneadas."}]}}'::jsonb where slug = 'birthday-funfetti' and i18n = '{}'::jsonb;

update public.settings
   set value = value || jsonb_build_object('announcementEs', 'Haz tu pedido con un día de anticipación para galletas recién horneadas')
 where key = 'business' and coalesce(value->>'announcementEs', '') = '';

update public.settings
   set value = value || jsonb_build_object('deliveryRadiusEs', 'a menos de 15 millas del estudio')
 where key = 'store' and coalesce(value->>'deliveryRadiusEs', '') = '';
